// <auto-generated />
using System;
using Inventarverwaltung1.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Inventarverwaltung1.Data.Migrations
{
    [DbContext(typeof(InventarverwaltungContainer))]
    [Migration("20260123083458_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbo")
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BenutzerFach", b =>
                {
                    b.Property<Guid>("Benutzer_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Fach_Id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Benutzer_Id", "Fach_Id");

                    b.HasIndex("Fach_Id");

                    b.ToTable("Benutzer_x_Fach", "dbo");
                });

            modelBuilder.Entity("BenutzerRolle", b =>
                {
                    b.Property<Guid>("Benutzer_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Rolle_Id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Benutzer_Id", "Rolle_Id");

                    b.HasIndex("Rolle_Id");

                    b.ToTable("Benutzer_x_Rolle", "dbo");
                });

            modelBuilder.Entity("BenutzerZustand", b =>
                {
                    b.Property<Guid>("Benutzer_Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Zustand_Id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Benutzer_Id", "Zustand_Id");

                    b.HasIndex("Zustand_Id");

                    b.ToTable("Benutzer_x_Zustand", "dbo");
                });

            modelBuilder.Entity("Inventarverwaltung1.Data.Abteilung", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Abteilung", "dbo");
                });

            modelBuilder.Entity("Inventarverwaltung1.Data.Ausleihe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Bemerkung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("BenutzerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("BisDatum")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("InventargegenstaendeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("VonDatum")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BenutzerId");

                    b.HasIndex("InventargegenstaendeId");

                    b.ToTable("Ausleihe", "dbo");
                });

            modelBuilder.Entity("Inventarverwaltung1.Data.Benutzer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Benutzer", "dbo");
                });

            modelBuilder.Entity("Inventarverwaltung1.Data.Fach", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Beschreibung")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Fach", "dbo");
                });

            modelBuilder.Entity("Inventarverwaltung1.Data.Gruppe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Gruppe", "dbo");
                });

            modelBuilder.Entity("Inventarverwaltung1.Data.Inventargegenstand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AbteilungId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("Anschaffungsdatum")
                        .HasColumnType("datetime2");

                    b.Property<string>("Bemerkung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Beschreibung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bezeichnung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("GruppeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("OrtId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Seriennummer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ZustandId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AbteilungId");

                    b.HasIndex("GruppeId");

                    b.HasIndex("OrtId");

                    b.HasIndex("ZustandId");

                    b.ToTable("Inventargegenstand", "dbo");
                });

            modelBuilder.Entity("Inventarverwaltung1.Data.Ort", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("RegalNr")
                        .HasColumnType("int");

                    b.Property<string>("RegalOrt")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Ort", "dbo");
                });

            modelBuilder.Entity("Inventarverwaltung1.Data.Rolle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Rolle", "dbo");
                });

            modelBuilder.Entity("Inventarverwaltung1.Data.Zustand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Beschreibung")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Zustand", "dbo");
                });

            modelBuilder.Entity("BenutzerFach", b =>
                {
                    b.HasOne("Inventarverwaltung1.Data.Benutzer", null)
                        .WithMany()
                        .HasForeignKey("Benutzer_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Inventarverwaltung1.Data.Fach", null)
                        .WithMany()
                        .HasForeignKey("Fach_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BenutzerRolle", b =>
                {
                    b.HasOne("Inventarverwaltung1.Data.Benutzer", null)
                        .WithMany()
                        .HasForeignKey("Benutzer_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Inventarverwaltung1.Data.Rolle", null)
                        .WithMany()
                        .HasForeignKey("Rolle_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BenutzerZustand", b =>
                {
                    b.HasOne("Inventarverwaltung1.Data.Benutzer", null)
                        .WithMany()
                        .HasForeignKey("Benutzer_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Inventarverwaltung1.Data.Zustand", null)
                        .WithMany()
                        .HasForeignKey("Zustand_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Inventarverwaltung1.Data.Ausleihe", b =>
                {
                    b.HasOne("Inventarverwaltung1.Data.Benutzer", "Benutzer")
                        .WithMany("Ausleihen")
                        .HasForeignKey("BenutzerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Inventarverwaltung1.Data.Inventargegenstand", "Inventargegenstaende")
                        .WithMany("Ausleihe")
                        .HasForeignKey("InventargegenstaendeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Benutzer");

                    b.Navigation("Inventargegenstaende");
                });

            modelBuilder.Entity("Inventarverwaltung1.Data.Inventargegenstand", b =>
                {
                    b.HasOne("Inventarverwaltung1.Data.Abteilung", "Abteilung")
                        .WithMany("Inventargegenstaende")
                        .HasForeignKey("AbteilungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Inventarverwaltung1.Data.Gruppe", "Gruppe")
                        .WithMany("Inventargegenstaende")
                        .HasForeignKey("GruppeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Inventarverwaltung1.Data.Ort", "Ort")
                        .WithMany("Inventargegenstaende")
                        .HasForeignKey("OrtId");

                    b.HasOne("Inventarverwaltung1.Data.Zustand", "Zustand")
                        .WithMany("Inventargegenstaende")
                        .HasForeignKey("ZustandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Abteilung");

                    b.Navigation("Gruppe");

                    b.Navigation("Ort");

                    b.Navigation("Zustand");
                });

            modelBuilder.Entity("Inventarverwaltung1.Data.Abteilung", b =>
                {
                    b.Navigation("Inventargegenstaende");
                });

            modelBuilder.Entity("Inventarverwaltung1.Data.Benutzer", b =>
                {
                    b.Navigation("Ausleihen");
                });

            modelBuilder.Entity("Inventarverwaltung1.Data.Gruppe", b =>
                {
                    b.Navigation("Inventargegenstaende");
                });

            modelBuilder.Entity("Inventarverwaltung1.Data.Inventargegenstand", b =>
                {
                    b.Navigation("Ausleihe");
                });

            modelBuilder.Entity("Inventarverwaltung1.Data.Ort", b =>
                {
                    b.Navigation("Inventargegenstaende");
                });

            modelBuilder.Entity("Inventarverwaltung1.Data.Zustand", b =>
                {
                    b.Navigation("Inventargegenstaende");
                });
#pragma warning restore 612, 618
        }
    }
}
