//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
//
//     Produced by Entity Framework Visual Editor v4.2.7.3
//     Source:                    https://github.com/msawczyn/EFDesigner
//     Visual Studio Marketplace: https://marketplace.visualstudio.com/items?itemName=michaelsawczyn.EFDesigner
//     Documentation:             https://msawczyn.github.io/EFDesigner/
//     License (MIT):             https://github.com/msawczyn/EFDesigner/blob/master/LICENSE
// </auto-generated>
//------------------------------------------------------------------------------

#nullable disable
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Runtime.CompilerServices;

namespace Inventarverwaltung1.Data
{
   public partial class Ausleihe
   {
      partial void Init();

      /// <summary>
      /// Default constructor
      /// </summary>
      public Ausleihe()
      {
         Init();
      }

      /// <summary>
      /// Public constructor with required data
      /// </summary>
      /// <param name="vondatum"></param>
      /// <param name="bisdatum"></param>
      /// <param name="benutzer"></param>
      /// <param name="inventargegenstaende"></param>
      public Ausleihe(DateTime vondatum, DateTime bisdatum, global::Inventarverwaltung1.Data.Benutzer benutzer, global::Inventarverwaltung1.Data.Inventargegenstand inventargegenstaende)
      {
         this.VonDatum = vondatum;

         this.BisDatum = bisdatum;

         if (benutzer == null) throw new ArgumentNullException(nameof(benutzer));
         this.Benutzer = benutzer;
         benutzer.Ausleihen.Add(this);

         if (inventargegenstaende == null) throw new ArgumentNullException(nameof(inventargegenstaende));
         this.Inventargegenstaende = inventargegenstaende;
         inventargegenstaende.Ausleihe.Add(this);

         Init();
      }

      /// <summary>
      /// Static create function (for use in LINQ queries, etc.)
      /// </summary>
      /// <param name="vondatum"></param>
      /// <param name="bisdatum"></param>
      /// <param name="benutzer"></param>
      /// <param name="inventargegenstaende"></param>
      public static Ausleihe Create(DateTime vondatum, DateTime bisdatum, global::Inventarverwaltung1.Data.Benutzer benutzer, global::Inventarverwaltung1.Data.Inventargegenstand inventargegenstaende)
      {
         return new Ausleihe(vondatum, bisdatum, benutzer, inventargegenstaende);
      }

      /*************************************************************************
       * Properties
       *************************************************************************/

      public string Bemerkung { get; set; }

      /// <summary>
      /// Required
      /// </summary>
      [Required]
      public DateTime BisDatum { get; set; }

      /// <summary>
      /// Identity, Indexed, Required
      /// Unique identifier
      /// </summary>
      [Key]
      [Required]
      [System.ComponentModel.Description("Unique identifier")]
      public Guid Id { get; set; }

      /// <summary>
      /// Required
      /// </summary>
      [Required]
      public DateTime VonDatum { get; set; }

      /*************************************************************************
       * Navigation properties
       *************************************************************************/

      /// <summary>
      /// Required
      /// </summary>
      public virtual global::Inventarverwaltung1.Data.Benutzer Benutzer { get; set; }

      /// <summary>
      /// Required
      /// </summary>
      public virtual global::Inventarverwaltung1.Data.Inventargegenstand Inventargegenstaende { get; set; }

   }
}

