//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
//
//     Produced by Entity Framework Visual Editor v4.2.7.3
//     Source:                    https://github.com/msawczyn/EFDesigner
//     Visual Studio Marketplace: https://marketplace.visualstudio.com/items?itemName=michaelsawczyn.EFDesigner
//     Documentation:             https://msawczyn.github.io/EFDesigner/
//     License (MIT):             https://github.com/msawczyn/EFDesigner/blob/master/LICENSE
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Inventarverwaltung1
{
   /// <inheritdoc/>
   public partial class InventarverwaltungContainer : DbContext
   {
      #region DbSets
      public virtual Microsoft.EntityFrameworkCore.DbSet<global::Inventarverwaltung1.Abteilung> Abteilung { get; set; }
      public virtual Microsoft.EntityFrameworkCore.DbSet<global::Inventarverwaltung1.Ausleihe> Ausleihe { get; set; }
      public virtual Microsoft.EntityFrameworkCore.DbSet<global::Inventarverwaltung1.Benutzer> Benutzer { get; set; }
      public virtual Microsoft.EntityFrameworkCore.DbSet<global::Inventarverwaltung1.Fach> Fach { get; set; }
      public virtual Microsoft.EntityFrameworkCore.DbSet<global::Inventarverwaltung1.Gruppe> Gruppe { get; set; }
      public virtual Microsoft.EntityFrameworkCore.DbSet<global::Inventarverwaltung1.Inventargegenstand> Inventargegenstand { get; set; }
      public virtual Microsoft.EntityFrameworkCore.DbSet<global::Inventarverwaltung1.Ort> Ort { get; set; }
      public virtual Microsoft.EntityFrameworkCore.DbSet<global::Inventarverwaltung1.Rolle> Rolle { get; set; }
      public virtual Microsoft.EntityFrameworkCore.DbSet<global::Inventarverwaltung1.Zustand> Zustand { get; set; }

      #endregion DbSets

      /// <inheritdoc />
      public InventarverwaltungContainer() : base()
      {
      }

      /// <summary>
      ///     <para>
      ///         Initializes a new instance of the <see cref="T:Microsoft.EntityFrameworkCore.DbContext" /> class using the specified options.
      ///         The <see cref="M:Microsoft.EntityFrameworkCore.DbContext.OnConfiguring(Microsoft.EntityFrameworkCore.DbContextOptionsBuilder)" /> method will still be called to allow further
      ///         configuration of the options.
      ///     </para>
      /// </summary>
      /// <param name="options">The options for this context.</param>
      public InventarverwaltungContainer(DbContextOptions<InventarverwaltungContainer> options) : base(options)
      {
      }

      partial void CustomInit(DbContextOptionsBuilder optionsBuilder);

      /// <inheritdoc />
      protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
      {
         optionsBuilder.UseLazyLoadingProxies();

         CustomInit(optionsBuilder);
      }

      partial void OnModelCreatingImpl(ModelBuilder modelBuilder);
      partial void OnModelCreatedImpl(ModelBuilder modelBuilder);

      /// <summary>
      ///     Override this method to further configure the model that was discovered by convention from the entity types
      ///     exposed in <see cref="T:Microsoft.EntityFrameworkCore.DbSet`1" /> properties on your derived context. The resulting model may be cached
      ///     and re-used for subsequent instances of your derived context.
      /// </summary>
      /// <remarks>
      ///     If a model is explicitly set on the options for this context (via <see cref="M:Microsoft.EntityFrameworkCore.DbContextOptionsBuilder.UseModel(Microsoft.EntityFrameworkCore.Metadata.IModel)" />)
      ///     then this method will not be run.
      /// </remarks>
      /// <param name="modelBuilder">
      ///     The builder being used to construct the model for this context. Databases (and other extensions) typically
      ///     define extension methods on this object that allow you to configure aspects of the model that are specific
      ///     to a given database.
      /// </param>
      protected override void OnModelCreating(ModelBuilder modelBuilder)
      {
         base.OnModelCreating(modelBuilder);
         OnModelCreatingImpl(modelBuilder);

         modelBuilder.HasDefaultSchema("dbo");

         modelBuilder.Entity<global::Inventarverwaltung1.Abteilung>()
                     .ToTable("Abteilung")
                     .HasKey(t => t.Id);
         modelBuilder.Entity<global::Inventarverwaltung1.Abteilung>()
                     .Property(t => t.Id)
                     .ValueGeneratedOnAdd()
                     .IsRequired();
         modelBuilder.Entity<global::Inventarverwaltung1.Abteilung>()
                     .HasMany<global::Inventarverwaltung1.Inventargegenstand>(p => p.Inventargegenstaende)
                     .WithOne(p => p.Abteilung)
                     .HasForeignKey("AbteilungId")
                     .IsRequired();

         modelBuilder.Entity<global::Inventarverwaltung1.Ausleihe>()
                     .ToTable("Ausleihe")
                     .HasKey(t => t.Id);
         modelBuilder.Entity<global::Inventarverwaltung1.Ausleihe>()
                     .Property(t => t.Id)
                     .ValueGeneratedOnAdd()
                     .IsRequired();
         modelBuilder.Entity<global::Inventarverwaltung1.Ausleihe>()
                     .Property(t => t.VonDatum)
                     .IsRequired();
         modelBuilder.Entity<global::Inventarverwaltung1.Ausleihe>()
                     .Property(t => t.BisDatum)
                     .IsRequired();

         modelBuilder.Entity<global::Inventarverwaltung1.Benutzer>()
                     .ToTable("Benutzer")
                     .HasKey(t => t.Id);
         modelBuilder.Entity<global::Inventarverwaltung1.Benutzer>()
                     .Property(t => t.Id)
                     .ValueGeneratedOnAdd()
                     .IsRequired();
         modelBuilder.Entity<global::Inventarverwaltung1.Benutzer>()
                     .HasMany<global::Inventarverwaltung1.Ausleihe>(p => p.Ausleihen)
                     .WithOne(p => p.Benutzer)
                     .HasForeignKey("BenutzerId")
                     .IsRequired();

         modelBuilder.Entity<global::Inventarverwaltung1.Fach>()
                     .ToTable("Fach")
                     .HasKey(t => t.Id);
         modelBuilder.Entity<global::Inventarverwaltung1.Fach>()
                     .Property(t => t.Id)
                     .ValueGeneratedOnAdd()
                     .IsRequired();
         modelBuilder.Entity<global::Inventarverwaltung1.Fach>()
                     .HasMany<global::Inventarverwaltung1.Benutzer>(p => p.Benutzer)
                     .WithMany(p => p.Faecher)
                     .UsingEntity<Dictionary<string, object>>(right => right.HasOne<global::Inventarverwaltung1.Benutzer>().WithMany().HasForeignKey("Benutzer_Id").OnDelete(DeleteBehavior.Cascade),left => left.HasOne<global::Inventarverwaltung1.Fach>().WithMany().HasForeignKey("Fach_Id").OnDelete(DeleteBehavior.Cascade),join => join.ToTable("Benutzer_x_Fach"));

         modelBuilder.Entity<global::Inventarverwaltung1.Gruppe>()
                     .ToTable("Gruppe")
                     .HasKey(t => t.Id);
         modelBuilder.Entity<global::Inventarverwaltung1.Gruppe>()
                     .Property(t => t.Id)
                     .ValueGeneratedOnAdd()
                     .IsRequired();
         modelBuilder.Entity<global::Inventarverwaltung1.Gruppe>()
                     .HasMany<global::Inventarverwaltung1.Inventargegenstand>(p => p.Inventargegenstaende)
                     .WithOne(p => p.Gruppe)
                     .HasForeignKey("GruppeId")
                     .IsRequired();

         modelBuilder.Entity<global::Inventarverwaltung1.Inventargegenstand>()
                     .ToTable("Inventargegenstand")
                     .HasKey(t => t.Id);
         modelBuilder.Entity<global::Inventarverwaltung1.Inventargegenstand>()
                     .Property(t => t.Seriennummer)
                     .IsRequired();
         modelBuilder.Entity<global::Inventarverwaltung1.Inventargegenstand>()
                     .Property(t => t.Id)
                     .ValueGeneratedOnAdd()
                     .IsRequired();
         modelBuilder.Entity<global::Inventarverwaltung1.Inventargegenstand>()
                     .Property(t => t.Beschreibung)
                     .IsRequired();
         modelBuilder.Entity<global::Inventarverwaltung1.Inventargegenstand>()
                     .HasMany<global::Inventarverwaltung1.Ausleihe>(p => p.Ausleihe)
                     .WithOne(p => p.Inventargegenstaende)
                     .HasForeignKey("InventargegenstaendeId")
                     .IsRequired();

         modelBuilder.Entity<global::Inventarverwaltung1.Ort>()
                     .ToTable("Ort")
                     .HasKey(t => t.Id);
         modelBuilder.Entity<global::Inventarverwaltung1.Ort>()
                     .Property(t => t.Id)
                     .ValueGeneratedOnAdd()
                     .IsRequired();
         modelBuilder.Entity<global::Inventarverwaltung1.Ort>()
                     .HasMany<global::Inventarverwaltung1.Inventargegenstand>(p => p.Inventargegenstaende)
                     .WithOne(p => p.Ort)
                     .HasForeignKey("OrtId");

         modelBuilder.Entity<global::Inventarverwaltung1.Rolle>()
                     .ToTable("Rolle")
                     .HasKey(t => t.Id);
         modelBuilder.Entity<global::Inventarverwaltung1.Rolle>()
                     .Property(t => t.Id)
                     .ValueGeneratedOnAdd()
                     .IsRequired();
         modelBuilder.Entity<global::Inventarverwaltung1.Rolle>()
                     .HasMany<global::Inventarverwaltung1.Benutzer>(p => p.Benutzer)
                     .WithMany(p => p.Rollen)
                     .UsingEntity<Dictionary<string, object>>(right => right.HasOne<global::Inventarverwaltung1.Benutzer>().WithMany().HasForeignKey("Benutzer_Id").OnDelete(DeleteBehavior.Cascade),left => left.HasOne<global::Inventarverwaltung1.Rolle>().WithMany().HasForeignKey("Rolle_Id").OnDelete(DeleteBehavior.Cascade),join => join.ToTable("Benutzer_x_Rolle"));

         modelBuilder.Entity<global::Inventarverwaltung1.Zustand>()
                     .ToTable("Zustand")
                     .HasKey(t => t.Id);
         modelBuilder.Entity<global::Inventarverwaltung1.Zustand>()
                     .Property(t => t.Id)
                     .ValueGeneratedOnAdd()
                     .IsRequired();
         modelBuilder.Entity<global::Inventarverwaltung1.Zustand>()
                     .HasMany<global::Inventarverwaltung1.Inventargegenstand>(p => p.Inventargegenstaende)
                     .WithOne(p => p.Zustand)
                     .HasForeignKey("ZustandId")
                     .IsRequired();

         OnModelCreatedImpl(modelBuilder);
      }
   }
}
