//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
//
//     Produced by Entity Framework Visual Editor v4.2.7.3
//     Source:                    https://github.com/msawczyn/EFDesigner
//     Visual Studio Marketplace: https://marketplace.visualstudio.com/items?itemName=michaelsawczyn.EFDesigner
//     Documentation:             https://msawczyn.github.io/EFDesigner/
//     License (MIT):             https://github.com/msawczyn/EFDesigner/blob/master/LICENSE
// </auto-generated>
//------------------------------------------------------------------------------

#nullable disable
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Runtime.CompilerServices;

namespace Inventarverwaltung1.Data
{
   public partial class Inventargegenstand
   {
      partial void Init();

      /// <summary>
      /// Default constructor
      /// </summary>
      public Inventargegenstand()
      {
         Ausleihe = new System.Collections.Generic.HashSet<global::Inventarverwaltung1.Data.Ausleihe>();

         Init();
      }

      /// <summary>
      /// Public constructor with required data
      /// </summary>
      /// <param name="seriennummer"></param>
      /// <param name="beschreibung"></param>
      /// <param name="gruppe"></param>
      /// <param name="zustand"></param>
      /// <param name="abteilung"></param>
      public Inventargegenstand(string seriennummer, string beschreibung, global::Inventarverwaltung1.Data.Gruppe gruppe, global::Inventarverwaltung1.Data.Zustand zustand, global::Inventarverwaltung1.Data.Abteilung abteilung)
      {
         if (string.IsNullOrEmpty(seriennummer)) throw new ArgumentNullException(nameof(seriennummer));
         this.Seriennummer = seriennummer;

         if (string.IsNullOrEmpty(beschreibung)) throw new ArgumentNullException(nameof(beschreibung));
         this.Beschreibung = beschreibung;

         if (gruppe == null) throw new ArgumentNullException(nameof(gruppe));
         this.Gruppe = gruppe;
         gruppe.Inventargegenstaende.Add(this);

         if (zustand == null) throw new ArgumentNullException(nameof(zustand));
         this.Zustand = zustand;
         zustand.Inventargegenstaende.Add(this);

         if (abteilung == null) throw new ArgumentNullException(nameof(abteilung));
         this.Abteilung = abteilung;
         abteilung.Inventargegenstaende.Add(this);

         Ausleihe = new System.Collections.Generic.HashSet<global::Inventarverwaltung1.Data.Ausleihe>();
         Init();
      }

      /// <summary>
      /// Static create function (for use in LINQ queries, etc.)
      /// </summary>
      /// <param name="seriennummer"></param>
      /// <param name="beschreibung"></param>
      /// <param name="gruppe"></param>
      /// <param name="zustand"></param>
      /// <param name="abteilung"></param>
      public static Inventargegenstand Create(string seriennummer, string beschreibung, global::Inventarverwaltung1.Data.Gruppe gruppe, global::Inventarverwaltung1.Data.Zustand zustand, global::Inventarverwaltung1.Data.Abteilung abteilung)
      {
         return new Inventargegenstand(seriennummer, beschreibung, gruppe, zustand, abteilung);
      }

      /*************************************************************************
       * Properties
       *************************************************************************/

      public DateTime? Anschaffungsdatum { get; set; }

      public string Bemerkung { get; set; }

      /// <summary>
      /// Required
      /// </summary>
      [Required]
      public string Beschreibung { get; set; }

      public string Bezeichnung { get; set; }

      /// <summary>
      /// Identity, Indexed, Required
      /// Unique identifier
      /// </summary>
      [Key]
      [Required]
      [System.ComponentModel.Description("Unique identifier")]
      public Guid Id { get; set; }

      /// <summary>
      /// Required
      /// </summary>
      [Required]
      public string Seriennummer { get; set; }

      /*************************************************************************
       * Navigation properties
       *************************************************************************/

      /// <summary>
      /// Required
      /// </summary>
      public virtual global::Inventarverwaltung1.Data.Abteilung Abteilung { get; set; }

      public virtual ICollection<global::Inventarverwaltung1.Data.Ausleihe> Ausleihe { get; private set; }

      /// <summary>
      /// Required
      /// </summary>
      public virtual global::Inventarverwaltung1.Data.Gruppe Gruppe { get; set; }

      public virtual global::Inventarverwaltung1.Data.Lagerort Ort { get; set; }

      /// <summary>
      /// Required
      /// </summary>
      public virtual global::Inventarverwaltung1.Data.Zustand Zustand { get; set; }

   }
}

